# Generated by Django 3.2.19 on 2023-06-25 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pan',
            name='vendor',
            field=models.CharField(choices=[('tefal', 'Tefal'), ('fissman', 'Fissman')], max_length=128),
        ),
        migrations.AlterField(
            model_name='potato',
            name='country',
            field=models.CharField(choices=[('bel', 'Беларусь'), ('rus', 'Россия')], max_length=128),
        ),
        migrations.AlterField(
            model_name='potato',
            name='id',
            field=models.CharField(default=uuid.UUID('489171ee-0ce8-4090-bb76-dee93801034f'), max_length=128, primary_key=True, serialize=False),
        ),
    ]
